---
- name: Deploy CI/CD Stack
  hosts: all
  become: true

  vars:
    project_name: 'fast_2024_t3'

  vars_files:
    - vars/vars.yml

  tasks:
  - name: Configure Server 
    block:
      - ansible.builtin.include_tasks: "config-server-{{ ansible_distribution | lower }}.yml"

      - name: Check if Docker Service is Up and Running
        ansible.builtin.service_facts:

      - name: Starting Deploy
        block:
          - name: Generate Docker Compose to Deploy Jenkins
            ansible.builtin.template:
              src: 'docker-compose.j2'
              dest: 'docker-compose.yml'

          - name: Deploy Jenkins on Docker Swarm
            community.docker.docker_stack:
              state: absent
              name: "{{ project_name }}"
              compose:
                - docker-compose.yml

          - name: Remove Temporary Files
            ansible.builtin.file:
              state: absent
              path: "{{ item }}"
            loop:
              - 'docker-compose.yml'

        when: ansible_facts.services['docker.service'].state == 'running'
    when: ansible_facts['system'] == 'Linux' or ansible_facts['system'] == 'Darwin'